name: 'Setup pseudocode-summarizer'
description: 'Installs pseudocode-summarizer CLI tool'
inputs:
  install-python:
    description: 'Whether to install Python 3.11 first'
    required: false
    default: 'false'
runs:
  using: 'node16'
  main: 'index.js'
